# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Outline installation tasks
  when: outline_enabled | bool
  tags:
    - setup-all
    - setup-outline
    - install-all
    - install-outline
  block:
    - name: Validate Outline configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Outline
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Outline uninstallation tasks
  when: not outline_enabled | bool
  tags:
    - setup-all
    - setup-outline
  block:
    - name: Uninstall Outline
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
