# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Outline systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ outline_identifier }}.service"
  register: outline_service_stat

- name: Uninstall Outline systemd services and files
  when: outline_service_stat.stat.exists | bool
  block:
    - name: Ensure Outline systemd service is stopped
      ansible.builtin.service:
        name: "{{ outline_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Outline systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ outline_identifier }}.service"
        state: absent

    - name: Ensure Outline support files do not exist
      ansible.builtin.file:
        path: "{{ outline_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Outline image source files path does not exist
      ansible.builtin.file:
        path: "{{ outline_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure Outline local data path if empty
      ansible.builtin.command:
        cmd: "rmdir {{ outline_data_path }}"
      register: outline_data_path_deletion_result
      changed_when: outline_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Outline base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ outline_base_path }}"
      register: outline_base_path_deletion_result
      changed_when: outline_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Outline container network does not exist
      when: outline_container_network_deletion_enabled
      block:
        - name: Ensure Outline container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ outline_container_network }}"
            state: absent
          register: outline_network_deletion_result

        - name: Ensure Outline container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ outline_container_network }}
          register: outline_network_deletion_result
          changed_when: outline_container_network in outline_network_deletion_result.stdout

- name: Check existence of Outline local data path
  ansible.builtin.stat:
    path: "{{ outline_data_path }}"
  register: outline_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Outline local data path
  when: outline_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Outline instance has been removed, local data remains in `" + outline_data_path + "`. Feel free to delete it."
        ]
      }}
