# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - {'old': 'outline_container_labels_traefik_forwardAuth_address_rd', 'new': 'outline_container_labels_traefik_forwardauth_address_rd'}

- name: Fail if required Outline settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - outline_identifier
    - outline_uid
    - outline_gid
    - outline_hostname
    - outline_path_prefix
    - outline_container_network
    - outline_environment_variable_secret_key
    - outline_environment_variable_utils_secret

# We need this validation check, because we initially only supported S3 storage and `outline_environment_variable_file_storage` did not exist.
# However, we'd like to (and do) default `outline_environment_variable_file_storage` to `local` now.
# People who are using S3 need to update their configuration to explicitly define their storage mechanism.
- name: Fail if outline_environment_variable_file_storage is local, but S3 credentials passed
  ansible.builtin.fail:
    msg: >-
      It seems like your configuration defines S3 credentials, but outline_environment_variable_file_storage is set to 'local' (the new default value).
      To continue using S3 for storage, add `outline_environment_variable_file_storage: s3` to your configuration.
  when: outline_environment_variable_file_storage == 'local' and outline_environment_variable_aws_access_key_id != ''

- name: Fail if outline_environment_variable_file_storage is s3, but S3 configuration is incomplete
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "outline_environment_variable_file_storage == 's3' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - outline_environment_variable_aws_access_key_id
    - outline_environment_variable_aws_secret_access_key
    - outline_environment_variable_aws_region
    - outline_environment_variable_aws_s3_upload_bucket_name

- name: Fail if encryption key is too short
  ansible.builtin.fail:
    msg: "outline_environment_variable_secret_key needs to be 64 chars long (ideally generated via `openssl rand -hex 32`)"
  when: outline_environment_variable_secret_key | length != 64

- name: Fail if Outline logging level is invalid
  ansible.builtin.fail:
    msg: >-
      outline_environment_variable_log_level must be 'error', 'warn', 'info', 'http', 'verbose', 'debug', or 'silly'
  when: "outline_environment_variable_log_level not in ['error', 'warn', 'info', 'http', 'verbose', 'debug', 'silly']"

- name: Run if Traefik is enabled
  when: outline_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Outline are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - outline_container_labels_traefik_hostname
        - outline_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `outline_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if outline_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          outline_container_labels_traefik_path_prefix (`{{ outline_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/outline`).
      when: "outline_container_labels_traefik_path_prefix != '/' and outline_container_labels_traefik_path_prefix[-1] == '/'"

    - name: Fail if outline_path_prefix is anything other than /
      ansible.builtin.fail:
        msg: >-
          `outline_path_prefix` must be set to `/`.
          See the comments for the `outline_path_prefix` variable in `defaults/main.yml`.
          Hosting Outline at a subdirectory may or may not work as expected - it will most likely require additional work.
      when: "outline_path_prefix != '/'"
